controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: position_controllers/JointTrajectoryController

position_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 2.0
      joint1: {trajectory: 0.1, goal: 0.1}
      joint2: {trajectory: 0.1, goal: 0.1}
      joint3: {trajectory: 0.1, goal: 0.1}
      joint4: {trajectory: 0.1, goal: 0.1}
      joint5: {trajectory: 0.1, goal: 0.1}
      joint6: {trajectory: 0.1, goal: 0.1}

    gains:
      joint1: {p: 50.0, i: 1.0, d: 1.0}
      joint2: {p: 50.0, i: 1.0, d: 1.0}
      joint3: {p: 50.0, i: 1.0, d: 1.0}
      joint4: {p: 50.0, i: 1.0, d: 1.0}
      joint5: {p: 50.0, i: 1.0, d: 1.0}
      joint6: {p: 50.0, i: 1.0, d: 1.0}
